### ISSUE TITLE
Not sure what I am doing wrong. Might be reddits new policies on API's

### ISSUE THREAD

**Issue by Speshals** [gpittarelli/reddit-twitch-bot#4]
Tried installing and it keeps spitting out this issue. http://image.prntscr.com/image/bce4ffe9726e4eff80ac00d43bdb949b.png
 It is saying on the subreddit my Twitch name but other than that it doesn't display link or title.

**Comment by andolf** [comment]
@Speshals I'm having the same issue. Did you find a solution for this problem?

**Comment by Speshals** [comment]
I did. It was me being stupid.

**Comment by andolf** [comment]
How? As I said, I'm having the same issue and you holding back your answer doesn't help me.

**Comment by gpittarelli** [comment]
@andolf Looks like a couple issues. I'll probably have to update the bot in future to support reddit's new authentication scheme (PRs welcome).

The error that is actually breaking the bot seems to be this: http://praw.readthedocs.io/en/stable/pages/faq.html#how-can-i-handle-captchas-myself if you run the bot at an interactive terminal with a DISPLAY, you should get prompted to complete a captcha
